name: 'Linter for OpenAPI'
description: 'Checks if the OpenAPI specification is correct according to PayGo rulesets'
inputs:
  registry:
    description: 'PayGo Docker registry'
    required: true
  mario-version:
    description: 'Mario Pipeline version to run linter'
    required: false
    default: 'v1'
  path-in:
    description: 'OpenAPI path'
    required: false
    default: 'target/swagger'
  file-name:
    description: 'OpenAPI file name'
    required: false
    default: 'swagger.json'
runs:
  using: "composite"
  steps:
    - run: |
        env > env-file 2>&1
        RESULT=`docker run --env-file ./env-file \
          -v ${{github.workspace}}/${{inputs.path-in}}:/swagger \
          ${{inputs.registry}}/mario-pipeline:${{inputs.mario-version}} \
          -s "/swagger/${{inputs.file-name}}" \
          -o "/swagger"`
        COMMAND_RESULT=$?
        echo "$RESULT" > mario-pipeline-log.txt 2>&1
        if [[ $RESULT == *"Valid OpenAPI file"* ]] && [[ $COMMAND_RESULT -eq 0 ]]; then
          echo "Valid yaml"
        else
          echo "Failed to validate yaml"
          echo "$RESULT"
          return 1
        fi
      shell: bash
