name: CI Validation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  validation:
    runs-on: paygo-clojure

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          bb -cp src --main test
